### ISSUE TITLE
Add live URL into the example code in the README

### ISSUE THREAD

**Issue by aldavidson** [ministryofjustice/postcodeinfo-client-php#2]
The example code uses https://postcodeinfo-staging.dsd.io as the URL - this is causing confusion amongst users when it doesn't work with the live API key they are given

**Comment by NSmithUK** [comment]
Will be fixed in v4 of the client.

**Comment by NSmithUK** [comment]
Resolved. The production URL no longer needs to be passed to the client.

Staging, testing, etc. urls can be passed via `baseUrl` if needed.
